### ISSUE TITLE
Technology Choice Overview and Suggestions

### ISSUE THREAD

**Issue by samkitsheth95** [SJSUFall2019-CMPE272/PlantDiseaseDetector#2]
* IBM Visual recognition:
I Understand IBM’s visual recognition will be used to train the models, but no further information is provided on how the model would be trained or how would IBM Watson’s Visual recognition will be integrated into your project. Will there be a custom model of IBM Visual Recognition or not.
Look at this:
https://cloud.ibm.com/docs/services/visual-recognition?topic=visual-recognition-customizing
 
* AWS Lambda :
As mentioned in the diagram AWS Lambda’s role in the project, it is difficult to figure out the use-case for aws lambda. Lambda as per diagram is getting its function from the node backend, which is being fed to IBM Visual Recognition. What functions are spinning in aws lambda, what is being fed to IBM Watson is not clear or mentioned. Also, I failed to understand why do you have lambda when you already have a node server.

* Kubernetes :
Will you be using multiple dockers and combining them using Kubernetes, for node and react then I don’t understand  Jenkins being a  part of your Kubernetes.

**Comment by raz4** [comment]
1. Yes, custom models will be trained and used.

2. The plan was to segregate data science from the node backend, so AWS Lambda was introduced. However, the cold start issues with AWS Lambda became apparent, so it was dismissed from the stack.

3. Eventually, an intermediate container to build the React was used, and the product was a single container with the React app and Node backend. Jenkins was planned for CI / CD. However, it has been replaced with an IBM Toolchain.

Thank you for the constructive feedback.
