### ISSUE TITLE
Possible cold start issue with AWS Lambda

### ISSUE THREAD

**Issue by s1ddh4nt** [SJSUFall2019-CMPE272/PlantDiseaseDetector#3]
**AWS Lambda** and other **serverless** technologies can face cold start issues. 
These issues can come up in two scenarios - 

1. As these technologies implement dynamic provisioning under the hood, applications that haven't been used in a while take time to start up and serve the incoming requests.
2. Also whenever the application needs to scale up, one of the idle containers is assigned with the additional incoming requests. This process is time consuming and hence event handling time increases.

This might increase the latency of the application and make it less responsive to the user. I would recommend you to read the following article to learn more about this issue and figure out possible workarounds for it - 
https://mikhail.io/2018/08/serverless-cold-start-war/

**Comment by raz4** [comment]
Noted. We'll look into deploying a service on Kubernetes to avoid the cold start problem.
