### ISSUE TITLE
Technical Viability of the solution

### ISSUE THREAD

**Issue by ronakshah2895** [SJSUFall2019-CMPE272/PlantDiseaseDetector#4]
In the abstract you have mentioned that farmers can train their own model, but I don’t see how it would be implemented from the description or the diagram, how the data obtained from the farmer is trained in IBM virtual recognition. It is unclear how the data will flow from the farmers all the way to IBM virtual recognition to train the model. Also note even if we assume that farmers do  send the data, it most likely will have to be converted to labelled datasets before feeding it to the AI.

**Comment by raz4** [comment]
A default model will be trained and used by default. The training dataset is stored on IBM Object Storage and fed into the IBM Visual Recognition for training. It is also possible to improve the model incrementally by images uploaded by farmers whether labelled or unlabelled. However, obtaining correctly labelled images from farmers will be a challenge, and a solution has yet to be developed.

Thank you for the feedback.
